# Generated by Django 4.0 on 2024-02-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='id',
            new_name='clinic_id',
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_contact_info',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
