# Generated by Django 4.0 on 2024-01-30 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('patient_national_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_contact_info', models.CharField(max_length=255)),
                ('patient_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHealth',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Patient.patientinfo')),
                ('age', models.IntegerField()),
                ('insurance', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_reserved_appointments', models.IntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patientinfo')),
            ],
        ),
    ]
