# Generated by Django 4.0 on 2024-02-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthealth',
            name='insurance',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='patient_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
